#to store category ids, keep no spaces
#category name not to be repeated
#keep synced with backend category DB Table

Electronics=1
    AudioDevices=2
        WirelessEarbuds=2
        PartySpeakers=4
        WirelessSpeakers=3
        WiredHeadphones=7
        Neckbands=8
        WiredEarphones=9
        Soundbars=8
        WirelessHeadphones=2
        Collections=3
    Powerbanks=6
    Smartwatches=6
    Cables=6
    MobileAccessories=8
        MobileCovers=7
    Chargers=9
################
BeautyandPersonalCare=5
    FaceCare=6
        Facewash=7
        FaceSerum=7
        Sunscreen=5
        FaceSerum=7
        FaceCream=6
        Moisturizer=5
        FaceMask=3
        FaceScrub=3
        Mists=6
        Exfoliators=5
        Cleansers=4
    HairCare=8
        Shampoo=9
        HairOil=5
        HairConditioner=5
        HairSerum=5
        HairMask=4
    Makeup=10
        Kits=6
        Lips=2
            Lipsticks=11
            LipstickSets=7
            LipBalm=6
        Eyes=6
            Kajal=5
            Kohl=8
            Eyeliner=6
            Mascara=8
            Eyebrow=7
        Face=5
            Foundation=5
            BBCream=5
            Compact=6
            Fixers=5
            Concealer=6
            Corrector=5
            Blush=6
            Palette=7
            Bronzer=6
            Contour=6
            Primer=2
            Highlighter=9
        Nail=7
    BodyCare=3
        BodyLotion=9
        Soap=8
        BodyWash=8
    BabyCare=8
        BabyShampoo=7
        BabyWash=4
        BabyBodyLotion=7
        BabySoap=9
        BabyOil=6
#################
Eyewear=12
    Men=5
        MensClassicEyeglasses=6
        MensPremiumEyeglasses=4
        MensScreenEyeglasses=4
        MensSunglasses=7
        MensPremiumSunglasses=7
    Women=5
        WomensClassicEyeglasses=6
        WomensPremiumEyeglasses=4
        WomensScreenEyeglasses=4
        WomensSunglasses=6
        WomensPremiumSunglasses=6
    Kids=13
        KidsClassicEyeglasses=6
        KidsScreenEyeglasses=4
        KidsSunglasses=6
    Lenses=4
        negSPHPowerCYL<0.5=4
        posSPHPowerCYL<0.5=3
        CYLPowerCYL>0.75=5
        ToricPower=4
####################
Fashion=2
    Caps=7
    MenCoOrdSets=6
    MenPlusSize=4
    MenTopwear=4
        MenTshirts=3
        MenOversizedTshirts=6
        MenCasualShirts=5
        MenHalfSleeveTshirts=7
        MenPrintedTshirts=6
        MenPlainTshirts=7
        MenCustomizedTshirts=3
        MenPoloTshirts=7
        MenFullSleeveTshirts=7
        MenHoodie=9
        MenSweatshirts=6
        MenJackets=5
        MenSweaters=9
        MenWindcheaters=5
    MenBottomwear=3
        MenJoggers=6
        MenTrackPants=6
        MenJeans=7
        MenPajamas=8
        MenShorts=6
        MenBoxers=7
        MenCargos=8
        MenParachutePants=8
        MenBaggyJeans=7
        MenFitJeans=7
        MenFitJeans=7
    MenFootwear=7
        MenSneakers=7
        MenClogs=6
        MenSliders=8
        MenCasualShoes=9
    WomenCoOrdSets=7
    WomenPlusSize=4
    WomenTopwear=4
        WomenOversizedTshirts=7
        WomenBoyfriendTshirts=9
        WomenClassicFitTshirts=5
        WomenAllShirts=4
        WomenHalfSleeveTshirts=8
        WomenPlainTshirts=8
        WomenCustomizedTshirts=6
        FashionTops=9
        WomenDresses=7
        WomenFullSleeveTshirts=4
        WomenHoodies=8
        WomenSweatshirts=6
        WomenJackets=6
        WomenSweaters=6
        WomenWindcheaters=7
    WomenBottomwear=3
        WomenJoggers=7
        WomenSweatpants=7
        WomenTrackpants=7
        WomenPants=8
        WomenJeans=8
        WomenPajamas=6
        WomenShorts=5
        WomenCargos=7
        WomenCargoJoggers=8
        WomenCargoPants=6
        WomenParachutePants=7
        WomenKoreanPants=6
        WomenWideLegJeans=8
        WomenBaggyJeans=7
        WomenStraightFitJeans=6
    WomenFootwear=6
        WomenSliders=9
#####################
BagsAndLuggage=7
    Briefcases=6
    Duffles=7
    TravelAccessories=9
    Bags=9
        Handbags=6
        SlingBags=7
        ToteBags=9
        DuffelBags=6
    Luggage=9
        CabinLuggage=8
        CheckInLuggage=3
        TrunkLuggage=9
        CheckInLargeLuggage=6
        LuggageSets=6
        KidsLuggage=6
    BackPacks=6
        WorkBackPacks=6
        DiaperBackPacks=6
        TravelBackPacks=5
        KidsBackPacks=6
        EverydayBackPacks=4
#########################
NutritionAndHealth=5
#######################
FoodAndDrink=4
    Namkeen=5
    DryFruits=6
        DryFruitsLadoos=7
        DryFruitsNutMix=8





