#to store category ids, keep no spaces
#category name not to be repeated
#keep synced with backend category DB Table

Electronics=1
    AudioDevices=2
        WirelessEarbuds=2
        PartySpeakers=4
        WirelessSpeakers=3
        WiredHeadphones=7
        Neckbands=8
        WiredEarphones=9
        Soundbars=8
        WirelessHeadphones=2
        Collections=3
    Powerbanks=6
    Smartwatches=6
    Cables=6
    MobileAccessories=8
    Chargers=9
################
BeautyandPersonalCare=5
    FaceCare=6
        Facewash=7
        FaceSerum=7
        Sunscreen=5
        FaceSerum=7
        FaceCream=6
        Moisturizer=5
        FaceMask=3
        FaceScrub=3
        Mists=6
        Exfoliators=5
        Cleansers=4
    HairCare=8
        Shampoo=9
        HairOil=5
        HairConditioner=5
        HairSerum=5
        HairMask=4
    Makeup=10
        Kits=6
        Lips=2
            Lipsticks=11
            LipstickSets=7
            LipBalm=6
        Eyes=6
            Kajal=5
            Kohl=8
            Eyeliner=6
            Mascara=8
            Eyebrow=7
        Face=5
            Foundation=5
            BBCream=5
            Compact=6
            Fixers=5
            Concealer=6
            Corrector=5
            Blush=6
            Palette=7
            Bronzer=6
            Contour=6
            Primer=2
            Highlighter=9
        Nail=7
    BodyCare=3
        BodyLotion=9
        Soap=8
        BodyWash=8
    BabyCare=8
        BabyShampoo=7
        BabyWash=4
        BabyBodyLotion=7
        BabySoap=9
        BabyOil=6
#################
Eyewear=12
    Men=5
        MensClassicEyeglasses=6
        MensPremiumEyeglasses=4
        MensScreenEyeglasses=4
        MensSunglasses=7
        MensPremiumSunglasses=7
    Women=5
        WomensClassicEyeglasses=6
        WomensPremiumEyeglasses=4
        WomensScreenEyeglasses=4
        WomensSunglasses=6
        WomensPremiumSunglasses=6
    Kids=13
        KidsClassicEyeglasses=6
        KidsScreenEyeglasses=4
        KidsSunglasses=6
    Lenses=4
        negSPHPowerCYL<0.5=4
        posSPHPowerCYL<0.5=3
        CYLPowerCYL>0.75=5
        ToricPower=4
####################
Fashion=2
    Men=2
        CoOrdSets=6
        Topwear=4
            Tshirts=3
            OversizedTshirts=6
            CasualShirts=5
            HalfSleeveTshirts=7
            PrintedTshirts=6
            PlainTshirts=7
            PlusSize=4
            CustomizedTshirts=3
            PoloTshirts=7
            FullSleeveTshirts=7
            Hoodie=9
            Sweatshirts=6
            Jackets=5
            Sweaters=9
            Windcheaters=5
        Bottomwear=3
            Joggers=6
            TrackPants=6
            Jeans=7
            Pajamas=8
            Shorts=6
            Boxers=7
            Cargos=8
            ParachutePants=8
            BaggyJeans=7
            FitJeans=7
            FitJeans=7
