#to store category ids, keep no spaces
#category name not to be repeated
#keep synced with backend category DB Table
#Current Category LEVEL: 1,2 (scrapping)
#implement level-3 categories when all the data is submitted by brands via website

Electronics=1
    AudioDevices=2
        WirelessEarbuds=2
        PartySpeakers=4
        HomeAudio=9
        WirelessSpeakers=3
        WiredHeadphones=7
        Neckbands=8
        WiredEarphones=9
        Soundbars=8
        WirelessHeadphones=2
        Collections=3
    Powerbanks=6
    Smartwatches=6
    Cables=6
    MobileAccessories=8
        MobileCovers=7
    Chargers=9
################
BeautyandPersonalCare=5
    FaceCare=6
        Facewash=7
        FaceSerum=7
        Sunscreen=5
        FaceSerum=7
        FaceCream=6
        Moisturizer=5
        FaceMask=3
        FaceScrub=3
        Mists=6
        Exfoliators=5
        Cleansers=4
        FaceCareCombos=8
        FacialOil=9
        Toner=8
    HairCare=8
        Shampoo=9
        HairOil=5
        HairConditioner=5
        HairSerum=5
        HairMask=4
    MakeupKits=6
    Lips=2
        Lipsticks=11
        LipstickSets=7
        LipBalm=6
    Eyes=6
        Eyepatches=8
        Kajal=5
        Kohl=8
        Eyeliner=6
        Mascara=8
        Eyebrow=7
        UnderEyeCream=9
    FaceMakeup=5
        Foundation=5
        BBCream=5
        Compact=6
        Fixers=5
        Concealer=6
        Corrector=5
        Blush=6
        Palette=7
        Bronzer=6
        Contour=6
        Primer=2
        Highlighter=9
    Nail=7
    BodyCare=3
        BodyLotion=9
        Soap=8
        BodyWash=8
        BodyScrubs=7
        BodySunscreen=8
        BodyShimmer=9
        BodyCareCombos=9
    BabyCare=8
        BabyShampoo=7
        BabyWash=4
        BabyBodyLotion=7
        BabySoap=9
        BabyOil=6
###################
Fragrances=9
    BodyPerfume=8
    MenFragrances=9
    WomenFragrances=7
#################
Eyewear=12
    Men=5
        MensEyeglasses=6
        MensScreenEyeglasses=4
        MensSunglasses=7
    Women=5
        WomensEyeglasses=6
        WomensScreenEyeglasses=4
        WomensSunglasses=6
    Kids=13
        KidsEyeglasses=6
        KidsScreenEyeglasses=4
        KidsSunglasses=6
    Lenses=4
        negSPHPowerCYL<0.5=4
        posSPHPowerCYL<0.5=3
        CYLPowerCYL>0.75=5
        ToricPower=4
####################
FashionAndClothing=2
    ShoeLaces=9
    Caps=7
    Socks=9
    MenCoOrdSets=6
    MenPlusSize=4
    ShoeInsoles=9
    BareFootSockShoes=9
    Masks=9
    DiyPatches=9
    MenBelts=9
    MenLoungewear=3
    MenTopwear=4
        MenTshirts=3
        MenCasualShirts=5
        MenOvershirt=7
        MenWinterwear=9
        MenWindcheaters=5
    MenBottomwear=3
        MenJoggers=6
        MenTrackPants=6
        MenJeans=7
        MenPajamas=8
        MenShorts=6
        MenBoxers=7
        MenCargos=8
        MenParachutePants=8
        MenBaggyJeans=7
        MenFitJeans=7
        MenTrousersAndPants=8
    MenFootwear=7
        MenSneakers=7
        MenClogs=6
        MenSliders=8
        MenCasualShoes=9
        MenMules=8
    WomenCoOrdSets=7
    WomenPlusSize=4
    WomenTopwear=4
        WomenTshirts=9
        WomenCasualShirts=4
        FashionTops=9
        WomenDresses=7
        WomenWinterwear=9
        WomenWindcheaters=7
        WomenBralettes=3
        AthleisureWear=7
    WomenBottomwear=3
        WomenJoggers=7
        WomenSweatpants=7
        WomenTrackpants=7
        WomenPants=8
        WomenJeans=8
        WomenPajamas=6
        WomenShorts=5
        WomenCargos=7
        WomenSkirts=6
        WomenCargoJoggers=8
        WomenCargoPants=6
        WomenParachutePants=7
        WomenKoreanPants=6
        WomenWideLegJeans=8
        WomenBaggyJeans=7
        WomenStraightFitJeans=6
    WomenFootwear=6
        WomenSliders=9
        WomenSneakers=7
        WomenMules=3
#####################
BagsAndLuggage=7
    Briefcases=6
    Duffles=7
    TravelAccessories=9
        LuggageCover=9
        LuggageTags=7
    Bags=9
        Handbags=6
        SlingBags=7
        ToteBags=9
        DuffelBags=6
    Luggage=9
        CabinLuggage=8
        CheckInLuggage=3
        TrunkLuggage=9
        CheckInLargeLuggage=6
        HardsideLuggage=4
        SoftsideLuggage=4
        BusinessLuggage=9
        LuggageSets=6
        KidsLuggage=6
    BackPacks=6
        PremiumBackPacks=3
        WorkBackPacks=6
        CollegeBackPacks=4
        DiaperBackPacks=6
        TravelBackPacks=5
        KidsBackPacks=6
        EverydayBackPacks=4
#######################
FoodAndDrink=4
    Pasta=9
    Namkeen=5
    Noodles=7
    PoppedChips=9
    Combos=4
############################
PetSupplies=8
    BedsMatsAndTents=7
    Cats=4
        CatFood=4
        CatTreats=6
        CatLitterSupplies=8
        CatToys=8
        CatPharmacy=6
        CatBedsAndMats=9
        CatWalkAndTravelSupplies=7
        CatClothing=8
        CatGroomingProducts=8
        CatHealthAndWellness=7
    Dogs=7
        DogFood=7
        DogTreats=8
        DogPharmacy=8
        DogWalkAndTravelEssentials=7
        DogTraining=7
        DogToys=7
        DogClothing=3
        DogGroomingProducts=4
        DogBedsAndMats=8
        DogBowlsAndFeeders=6
########################
HomeAndKitchen=7
    KidsRoom=9
        KidsAccessories=9
        KidsFurniture=8
    Cleaning=9
        DishAndKitchenCare=6
        LaundryAndFabricCare=6
        BathroomAndToiletCare=9
        CleaningAccessories=8
        FloorAndSurfaceCare=6
        Handwashes=8
        DelicateSurfaceCleaners=7
        CleaningCombos=8
        InsectRepellents=9
    Decor=9
    Kitchen=0
        DiningFurniture=5
        DrinkWare=8
        DinnerWare=8
        Serveware=9
        Cookware=9
        KitchenStorages=8
    Living=0
        Storages=9
        Curtains=8
        HomeOfficeFurniture=9
        StudyTable=9
        WallShelf=9
        Lamps=9
        Chairs=9
        Tables=7
        TVUnits=9
        SofaSet=8
        PlusSizeSofaSet=8
        Beds=9
        Wardrobes=8
        BookShelves=9
        TableLinens=9
    Tiles=9
    FloorFurnishings=9
    PregnancyAndMaternity=7
    Bath=8
        Towels=9
        KidsTowels=9
        Mats=8
        Bathrobes=8
    Bedding=8
        Cushions=7
        Mattress=8
        PlusSizeMattress=0
        Rugs=9
        CushionCovers=4
        Pillows=8
######################3
HealthAndNutrition=4
    DryFruits=6
            DryFruitsLadoos=7
            DryFruitsNutMix=8
    CoatedPeanuts=9
    PeanutButter=8
    Protein=3
        ProteinPowder=9
    Oats=9
    Muesli=9
    CornFlakes=9
    Orthotics=8
        OrthoticsFootwear=8
        OrthoticsCushions=5
        OrthoticsPillows=3
        OrthoticsShoeInsoles=7
        OrthoticsBareFootSockShoes=8
######################
ToyKidsAndBaby=3
    KidsWearBoys=4
    KidsWearGirls=3
    BabyKidsFood=7
        BabyCereals=9
        Noodles=3
        Pasta=4
        MilkMixes=9
        Cookies=8
        KidsCereals=8
        Cakes=5
        PanCakeMix=9
        DosaMix=9
        UpmaMix=9
        NaturalSweetners=7
    Books=8
        ComicBooks=8
    Toys=8






